name: fastai
channels:
- fastai
- pytorch
- defaults
dependencies:
- fastcore>=1.3.8
- torchvision>=0.8
- matplotlib
- pandas>=1.0.0
- requests
- pyyaml
- fastprogress>=0.2.4
- pillow>=9.1.1
- scikit-learn
- scipy
- spacy
- pytorch>=1.7.0

