name: fastai2
channels:
- fastai
- pytorch
- defaults
dependencies:
- jupyter
- pytorch>=1.2.0,<1.4.0
- torchvision<=0.4.2
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress>=0.1.22
- pillow
- python>=3.6
- pip
- scikit-learn
- scipy
- spacy

